const routes = {
  home: '/',
  shop: '/shop',
  search: '/search',
  detail: '/product-single',
  singleProduct: '/product-single/:id',
  checkout: '/checkout',
  cart: '/cart',
  login: '/login',
  signup: '/signup',
  forgot: '/forgot-password',
  profile: '/profile',
  aboutUs: '/about-us',
  withList: '/with-list',
  editProfile: '/edit-profile',
  history: '/history',
  historyDetail: '/history/:id',
  chat: '/chat',
  direction: '/direction',
  directionLogin: 'direction-login',
  confirmOpt: '/confirm-opt',
  resetPassword: '/reset-password/:id',
};

export default routes;
